"use client";

import type { Metadata } from "next";
import React, { useState } from "react";
import "./globals.css";
import Providers from "./provider";
import Header from "./header/header";
import Sidebar from "./sidebar/sidebar";

// export const metadata: Metadata = {
//   title: "Todo Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [sidebarOpen, setSidebarOpen] = useState(false);

  return (
    <html lang="en">
      <body className="bg-[#0a0a0f]">
        <Providers>
          {/* Header */}
          <div className="fixed inset-x-0 top-0 z-30">
            <Header sidebarOpen={sidebarOpen} setSidebarOpen={setSidebarOpen} />
          </div>

       <div className="fixed top-16">
          <Sidebar sidebarOpen={sidebarOpen} setSidebarOpen={setSidebarOpen} />
       </div>

          {/* Main content */}
          <main className="pt-16 md:ml-64 p-4 transition-all duration-300">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}